#!/bin/bash
# Deployment Script for Render

echo "🚀 Deploying Chip Happens Stripe Server to Render"
echo "=================================================="
echo ""
echo "📋 DEPLOYMENT STEPS:"
echo ""
echo "1. Go to: https://render.com"
echo "2. Sign up or log in"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Choose 'Deploy an existing image from a registry' → 'Public Git repository'"
echo "5. Enter your repository URL (or connect GitHub)"
echo ""
echo "📝 CONFIGURATION:"
echo ""
echo "Name: chip-happens-stripe-server"
echo "Region: Oregon (US West) or closest to you"
echo "Branch: main (or your branch name)"
echo "Root Directory: (leave empty)"
echo "Runtime: Node"
echo "Build Command: npm install"
echo "Start Command: node stripe-server.js"
echo "Plan: Free"
echo ""
echo "🔑 ENVIRONMENT VARIABLES TO ADD:"
echo ""
echo "STRIPE_SECRET_KEY = sk_test_51SDRD2KLsgahIll1V81w8mkMxJxuE2ar0GWiSqtbmpBvSHjJvKbWzS2InQV1qiiPwpZ7BH0WAfdS6LbsW8RQ7B5w00L3kJQOSe"
echo "FRONTEND_URL = http://localhost:8100"
echo "PORT = 4242"
echo ""
echo "⚠️  NOTE: After deployment, Render will give you a URL like:"
echo "    https://chip-happens-stripe-server.onrender.com"
echo ""
echo "📌 NEXT STEPS AFTER DEPLOYMENT:"
echo "1. Copy your Render URL"
echo "2. Update your frontend .env file:"
echo "   REACT_APP_STRIPE_API_URL=https://your-render-url.onrender.com"
echo "3. When you deploy frontend, update FRONTEND_URL on Render to match"
echo ""
echo "✅ Done! Your server will be live in 2-3 minutes!"
